// GitOps/Jenkinsfile
pipeline {
    agent { label 'Node' }

    parameters {
        string(name: 'FRONTEND_DOCKER_TAG', defaultValue: '', description: 'Frontend image tag to deploy')
        string(name: 'BACKEND_DOCKER_TAG', defaultValue: '', description: 'Backend image tag to deploy')
    }

    stages {
        stage('Deploy to K8s') {
            steps {
                script {
                    // This calls your pipelineDeploy module from the Shared Library
                    pipelineDeploy.gitopsUpdate(
                        cfg: [
                            gitOpsRepoUrl: 'https://github.com/shubhamsingh74888/Wanderlust-Mega-Project.git',
                            k8sManifestsDir: 'kubernetes',
                            deployEnvironment: 'prod',
                            frontendImageTag: params.FRONTEND_DOCKER_TAG,
                            backendImageTag: params.BACKEND_DOCKER_TAG,
                            gitCredId: 'github-token'
                        ],
                        utils: new org.wanderlust.Utils(this)
                    )
                }
            }
        }
    }
}
